[package]
name = "simplification"
version = "1.0.0"
authors = ["Costa Group UCM"]
edition = "2018"

description = "applies simplification to zk circuits"
keywords = ["zkproofs", "zksanrks","circuits","compiler"]
categories = ["compilers"]

[dependencies]
circom_algebra = {path = "../circom_algebra"}
clap = "2.33.0"
ansi_term = "0.12.1"
wast = "39.0.0"
exitcode = "1.1.2"
num-bigint-dig = "0.6.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
threadpool = "1.0"
num_cpus = "1.0"
